DROP DATABASE IF EXISTS THUEXE
GO

CREATE DATABASE THUEXE
GO

USE THUEXE
GO

CREATE TABLE LOAIXE (
	IDLoaiXe int IDENTITY(1,1) PRIMARY KEY,
	TenLoaiXe NVARCHAR(50) NOT NULL,
	TomTat NVARCHAR(MAX),
	ChiTiet NVARCHAR(MAX),
	GiaTheoGio MONEY,
	GiaTheoNgay MONEY,
	SoLuotThue INT,
	HinhAnh VARBINARY(MAX)
)
CREATE TABLE HIEUXE (
	IDHieuXe int IDENTITY(1,1) PRIMARY KEY,
	TenHieuXe NVARCHAR(50) NOT NULL,
	TomTat NVARCHAR(MAX),
	ChiTiet NVARCHAR(MAX),
	SoLuotThue INT,
	HinhAnh VARBINARY(MAX)
)
CREATE TABLE XE (
	IDXe int IDENTITY(1,1) PRIMARY KEY,
	IDLoaiXe int FOREIGN KEY REFERENCES LOAIXE(IDLoaiXe),
	IDHieuXe int FOREIGN KEY REFERENCES HIEUXE(IDHieuXe),
	TenXe VARCHAR(50),
	BienSoXe CHAR(15)
)
CREATE TABLE KHACH (
	IDKhach int IDENTITY(1,1) PRIMARY KEY,
	TenKhach NVARCHAR(50),
	SDT VARCHAR(12),
	DiaChi NVARCHAR(50),
	Email VARCHAR(50)
)
CREATE TABLE SOTHUEXE (
	IDThue int IDENTITY(1,1) PRIMARY KEY,
	IDKhach int FOREIGN KEY REFERENCES KHACH(IDKhach),
	NgayTao DATE,
	ThoiGianThue datetime,
	ThoiGianTra datetime,
	TongTien money,
	TongGiam money,
	GhiChu NVARCHAR(128),
	TinhTrangThue NVARCHAR(10)
)
CREATE TABLE THUECT (
	IDThueCT int IDENTITY(1,1) PRIMARY KEY,
	IDThue int FOREIGN KEY REFERENCES SOTHUEXE(IDThue),
	IDXe int FOREIGN KEY REFERENCES XE(IDXe),
	Gia MONEY
)
CREATE TABLE YEUCAUTHUE(
	IDYeuCau int IDENTITY(1,1) PRIMARY KEY,
	IDHieuXe int FOREIGN KEY REFERENCES HIEUXE(IDHieuXe),
	IDLoaiXe int FOREIGN KEY REFERENCES LOAIXE(IDLoaiXe),
	NgayTao DATE,
	TenKhach NVARCHAR(50),
	SDT VARCHAR(12),
	DiaChi NVARCHAR(50),
	Email VARCHAR(50),
	ThoiGianThue datetime,
	ThoiGianTra datetime,
	YeuCauKhac NVARCHAR(128),
	TrangThai BIT
)
CREATE TABLE PHANHOI(
	IDPhanHoi INT IDENTITY(1,1) PRIMARY KEY,
	ThoiGianPhanHoi DATETIME,
	TenKhach NVARCHAR(50),
	SDT VARCHAR(12),
	DiaChi NVARCHAR(50),
	Email VARCHAR(50),
	TieuDe NVARCHAR(50) NOT NULL,
	NoiDung NVARCHAR(MAX) NOT NULL,
	DaXuLy bit
)
CREATE TABLE THONGKE(
	IDThongKe INT IDENTITY(1,1) PRIMARY KEY,
	Thang int NOT NULL,
	Nam int NOT NULL,
	TongDoanhThu MONEY,
	TongSoLuotThue int
)
CREATE TABLE TAIKHOAN(
	IDTaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
	Username VARCHAR(30),
	Password VARCHAR(30),
	ThoiGianDangNhap DATETIME
)
CREATE TABLE HOADON (
	IDHoaDon int IDENTITY(1,1) PRIMARY KEY,
	IDKhach int FOREIGN KEY REFERENCES KHACH(IDKhach),
	IDThue int FOREIGN KEY REFERENCES SOTHUEXE(IDThue),
	NgayTao DATE,
	ThoiGianThue datetime,
	ThoiGianTra datetime,
	TongTien money,
	TongGiam money,
	GhiChu NVARCHAR(128),
	TinhTrangThue NVARCHAR(10)
)
CREATE TABLE HOADONCT (
	IDHDCT int IDENTITY(1,1) PRIMARY KEY,
	IDHoaDon int FOREIGN KEY REFERENCES HOADON(IDHoaDon),
	IDXe int FOREIGN KEY REFERENCES XE(IDXe),
	Gia MONEY
)
