CREATE DATABASE THUEXE
GO

USE THUEXE
GO

CREATE TABLE LOAIXE (
	IDLoai int IDENTITY(1,1) PRIMARY KEY,
	SoCho int
)
CREATE TABLE XE (
	IDXe int IDENTITY(1,1) PRIMARY KEY,
	IDLoai int FOREIGN KEY REFERENCES LOAIXE(IDLoai),
	TenXe VARCHAR(50),
	HinhAnhXe varbinary(max)
)
CREATE TABLE BANGBAOGIA (
	IDBangBG int IDENTITY(1,1) PRIMARY KEY,
	IDXe int FOREIGN KEY REFERENCES XE(IDXe),
	GiaTheoGio money,
	GiaTheoNgay money
)
CREATE TABLE KHACH (
	IDKhach int IDENTITY(1,1) PRIMARY KEY,
	TenKhach NVARCHAR(50),
	SDT VARCHAR(12),
	DiaChi NVARCHAR(50),
	CMND VARCHAR(15)
)
CREATE TABLE THUE (
	IDThue int IDENTITY(1,1) PRIMARY KEY,
	IDKhach int FOREIGN KEY REFERENCES KHACH(IDKhach),
	IDBangBG int FOREIGN KEY REFERENCES BANGBAOGIA(IDBangBG),
	ThoiGianBD datetime,
	ThoiGianTra datetime
)
