//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGBAOGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANGBAOGIA()
        {
            this.THUEs = new HashSet<THUE>();
            this.THUEs1 = new HashSet<THUE>();
        }
    
        public int IDBangBG { get; set; }
        public Nullable<int> IDXe { get; set; }
        public Nullable<decimal> GiaTheoGio { get; set; }
        public Nullable<decimal> GiaTheoNgay { get; set; }
    
        public virtual XE XE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUE> THUEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUE> THUEs1 { get; set; }
    }
}
