//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUE
    {
        public int IDThue { get; set; }
        public Nullable<int> IDKhach { get; set; }
        public Nullable<int> IDBangBG { get; set; }
        public Nullable<System.DateTime> ThoiGianBD { get; set; }
        public Nullable<System.DateTime> ThoiGianTra { get; set; }
    
        public virtual BANGBAOGIA BANGBAOGIA { get; set; }
        public virtual BANGBAOGIA BANGBAOGIA1 { get; set; }
        public virtual KHACH KHACH { get; set; }
        public virtual KHACH KHACH1 { get; set; }
    }
}
