//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.BANGBAOGIAs = new HashSet<BANGBAOGIA>();
        }
    
        public int IDXe { get; set; }
        public Nullable<int> IDLoai { get; set; }
        public string TenXe { get; set; }
        public byte[] HinhAnhXe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGBAOGIA> BANGBAOGIAs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
    }
}
