//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUCAUTHUE
    {
        public int IDYeuCau { get; set; }
        public Nullable<int> IDKhach { get; set; }
        public Nullable<int> IDHieuXe { get; set; }
        public Nullable<int> IDLoaiXe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> ThoiGianThue { get; set; }
        public Nullable<System.DateTime> ThoiGianTra { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string YeuCauKhac { get; set; }
    
        public virtual HIEUXE HIEUXE { get; set; }
        public virtual KHACH KHACH { get; set; }
    }
}
