//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LienHe
    {
        public int ID { get; set; }
        [MaxLength(50,ErrorMessage ="Tên không được quá 50 ký tự")]
        [Required(ErrorMessage ="Phải nhập tên")]
        public string Name { get; set; }
        [MaxLength(50, ErrorMessage = "Địa chỉ không được quá 50 ký tự")]
        [Required(ErrorMessage = "Phải nhập địa chỉ")]
        public string Address { get; set; }
        [MaxLength(50, ErrorMessage = "Mail không được quá 50 ký tự")]
        [Required(ErrorMessage = "Phải nhập mail")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Phải nhập số điện thoại")]
        public int Phone { get; set; }
        [MaxLength(50, ErrorMessage = "Tiêu đề không được quá 50 ký tự")]
        [Required(ErrorMessage = "Phải nhập tiêu đề")]
        public string Title { get; set; }
        [DataType(DataType.MultilineText)]
        [MaxLength(200, ErrorMessage = "Nội dung không được quá 200 ký tự")]
        [Required(ErrorMessage = "Phải nhập nội dung")]
        
        public string Content { get; set; }
    }
}
