//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIEUXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HIEUXE()
        {
            this.XEs = new HashSet<XE>();
            this.YEUCAUTHUEs = new HashSet<YEUCAUTHUE>();
            this.SOTHUEXEs = new HashSet<SOTHUEXE>();
        }
    
        public int IDHieuXe { get; set; }
        public string TenHieuXe { get; set; }
        public string TomTat { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> SoLuotThue { get; set; }
        public byte[] HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XE> XEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUCAUTHUE> YEUCAUTHUEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOTHUEXE> SOTHUEXEs { get; set; }
    }
}
