//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.HOADONCTs = new HashSet<HOADONCT>();
        }
    
        public int IDHoaDon { get; set; }
        public Nullable<int> IDKhach { get; set; }
        public Nullable<int> IDThue { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> ThoiGianThue { get; set; }
        public Nullable<System.DateTime> ThoiGianTra { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TongGiam { get; set; }
        public string GhiChu { get; set; }
        public string TinhTrangThue { get; set; }
    
        public virtual KHACH KHACH { get; set; }
        public virtual SOTHUEXE SOTHUEXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONCT> HOADONCTs { get; set; }
    }
}
