//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOI
    {
        public int IDPhanHoi { get; set; }
        public Nullable<System.DateTime> ThoiGianPhanHoi { get; set; }
        public string TenKhach { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> DaXuLy { get; set; }
    }
}
