//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUE
    {
        public int IDThue { get; set; }
        public Nullable<int> IDKhach { get; set; }
        public Nullable<int> IDBangBG { get; set; }
        public Nullable<int> IDXe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> ThoiGianThue { get; set; }
        public Nullable<System.DateTime> ThoiGianTra { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TienDatCoc { get; set; }
        public Nullable<decimal> TienConLai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BANGBAOGIA BANGBAOGIA { get; set; }
        public virtual KHACH KHACH { get; set; }
        public virtual XE XE { get; set; }
    }
}
