//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUECT
    {
        public int IDThueCT { get; set; }
        public Nullable<int> IDThue { get; set; }
        public Nullable<int> IDXe { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual SOTHUEXE SOTHUEXE { get; set; }
        public virtual XE XE { get; set; }
    }
}
