//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Không được để trống !")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Không được để trống !")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string LoginMessageError { get; set; }
    }
}
