//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.HOADONCTs = new HashSet<HOADONCT>();
            this.THUECTs = new HashSet<THUECT>();
        }
    
        public int IDXe { get; set; }
        public Nullable<int> IDLoaiXe { get; set; }
        public Nullable<int> IDHieuXe { get; set; }
        public string TenXe { get; set; }
        public string BienSoXe { get; set; }
    
        public virtual HIEUXE HIEUXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONCT> HOADONCTs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUECT> THUECTs { get; set; }
    }
}
